// Minimal read-only XLSX support, so a DIM point list can be imported straight
// from the Excel file it is maintained in instead of being exported to CSV
// first.
//
// Hand-rolled rather than pulled from a library, for the same reason the ZIP
// *writer* in lib/zip.ts is: the npm-published SheetJS build is a stale
// snapshot carrying known advisories, and the maintained build is not on npm.
// What an XLSX actually needs is small — a ZIP directory walk, `deflate-raw`
// (which the platform provides via DecompressionStream), and two XML shapes —
// so the whole reader fits in one file with no supply chain attached.
//
// Scope is deliberately narrow: the first worksheet, as a grid of strings.
// Formulas are read at their cached value, which is what a spreadsheet shows
// and therefore what the user means.

// ── ZIP reading ────────────────────────────────────────────────────────────

interface ZipEntry {
  name: string;
  method: number;
  compressedSize: number;
  localHeaderOffset: number;
}

// Walk the central directory backwards from the End Of Central Directory
// record. The EOCD sits at the very end unless the archive carries a trailing
// comment, hence the bounded scan.
function readCentralDirectory(view: DataView): ZipEntry[] {
  const len = view.byteLength;
  const maxScan = Math.min(len, 0xffff + 22);
  let eocd = -1;
  for (let i = len - 22; i >= len - maxScan; i--) {
    if (i < 0) break;
    if (view.getUint32(i, true) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error("not-a-zip");

  const count = view.getUint16(eocd + 10, true);
  let ptr = view.getUint32(eocd + 16, true);

  const entries: ZipEntry[] = [];
  for (let i = 0; i < count; i++) {
    if (view.getUint32(ptr, true) !== 0x02014b50) break;
    const method = view.getUint16(ptr + 10, true);
    const compressedSize = view.getUint32(ptr + 20, true);
    const nameLen = view.getUint16(ptr + 28, true);
    const extraLen = view.getUint16(ptr + 30, true);
    const commentLen = view.getUint16(ptr + 32, true);
    const localHeaderOffset = view.getUint32(ptr + 42, true);
    const nameBytes = new Uint8Array(view.buffer, view.byteOffset + ptr + 46, nameLen);
    entries.push({
      name: new TextDecoder().decode(nameBytes),
      method,
      compressedSize,
      localHeaderOffset,
    });
    ptr += 46 + nameLen + extraLen + commentLen;
  }
  return entries;
}

async function inflate(raw: Uint8Array, method: number): Promise<Uint8Array> {
  if (method === 0) return raw; // stored
  if (method !== 8) throw new Error(`unsupported-compression-${method}`);
  const stream = new Blob([raw as BlobPart]).stream().pipeThrough(new DecompressionStream("deflate-raw"));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

async function readEntry(buf: ArrayBuffer, view: DataView, entry: ZipEntry): Promise<string> {
  const off = entry.localHeaderOffset;
  if (view.getUint32(off, true) !== 0x04034b50) throw new Error("bad-local-header");
  // The local header repeats the name/extra lengths, and its extra field can
  // differ in length from the central directory's — always read them here.
  const nameLen = view.getUint16(off + 26, true);
  const extraLen = view.getUint16(off + 28, true);
  const dataStart = off + 30 + nameLen + extraLen;
  const raw = new Uint8Array(buf, dataStart, entry.compressedSize);
  return new TextDecoder().decode(await inflate(raw, entry.method));
}

// ── XML scanning ───────────────────────────────────────────────────────────
// A purpose-built scanner rather than DOMParser: DOMParser exists only in the
// browser, which would make this module untestable outside one and would pull
// a full HTML/XML engine in to read four tag shapes. The files here are
// machine-generated by Excel and always well-formed, so scanning for the
// specific elements the format defines is both sufficient and predictable.

interface XmlElement {
  attrs: Record<string, string>;
  inner: string;
}

const ENTITIES: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'" };

function decodeXml(text: string): string {
  if (!text.includes("&")) return text;
  return text.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z]+);/g, (whole, body: string) => {
    if (body[0] === "#") {
      const code = body[1] === "x" || body[1] === "X" ? parseInt(body.slice(2), 16) : parseInt(body.slice(1), 10);
      return Number.isFinite(code) ? String.fromCodePoint(code) : whole;
    }
    return ENTITIES[body] ?? whole;
  });
}

function parseAttrs(raw: string): Record<string, string> {
  const attrs: Record<string, string> = {};
  const re = /([\w:.-]+)\s*=\s*"([^"]*)"|([\w:.-]+)\s*=\s*'([^']*)'/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(raw)) !== null) {
    attrs[m[1] ?? m[3]] = decodeXml(m[2] ?? m[4] ?? "");
  }
  return attrs;
}

// Every <name> element at any depth, in document order. Handles self-closing
// tags and nesting of the same element name.
function* elements(xml: string, name: string): Generator<XmlElement> {
  const open = new RegExp(`<${name}(\\s[^>]*?)?(/?)>`, "g");
  let m: RegExpExecArray | null;
  while ((m = open.exec(xml)) !== null) {
    const attrs = parseAttrs(m[1] ?? "");
    if (m[2] === "/") {
      yield { attrs, inner: "" };
      continue;
    }
    // Walk forward tracking depth so a nested <name> doesn't end this element.
    const scan = new RegExp(`<${name}(?:\\s[^>]*?)?(/?)>|</${name}>`, "g");
    scan.lastIndex = open.lastIndex;
    let depth = 1;
    let end = -1;
    let s2: RegExpExecArray | null;
    while ((s2 = scan.exec(xml)) !== null) {
      if (s2[0].startsWith("</")) {
        if (--depth === 0) {
          end = s2.index;
          break;
        }
      } else if (s2[1] !== "/") {
        depth++;
      }
    }
    if (end < 0) return; // truncated document
    yield { attrs, inner: xml.slice(open.lastIndex, end) };
    open.lastIndex = scan.lastIndex;
  }
}

// Concatenated text of every <t> in `xml`, skipping <rPh> (phonetic hints for
// East Asian text, which are not part of the cell's value).
function textOfRuns(xml: string): string {
  const withoutPhonetics = xml.replace(/<rPh[\s\S]*?<\/rPh>/g, "");
  let out = "";
  for (const t of elements(withoutPhonetics, "t")) out += decodeXml(t.inner);
  return out;
}

function firstValue(xml: string, name: string): string | null {
  for (const el of elements(xml, name)) return decodeXml(el.inner);
  return null;
}

// "BC" -> 54 (0-based). Column refs are bijective base-26.
function columnIndex(ref: string): number {
  let n = 0;
  for (const ch of ref) {
    const code = ch.charCodeAt(0);
    if (code < 65 || code > 90) break;
    n = n * 26 + (code - 64);
  }
  return n - 1;
}

// Excel stores dates as a day count from 1899-12-30 (the offset absorbs the
// deliberate 1900 leap-year bug). Only applied by callers that know a column
// is a date — reading styles.xml to detect that automatically is far more
// machinery than this import needs.
export function excelSerialToISO(serial: number): string | null {
  if (!Number.isFinite(serial) || serial < 20000 || serial > 80000) return null;
  const ms = Math.round((serial - 25569) * 86400 * 1000);
  const d = new Date(ms);
  return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
}

// ── Public API ─────────────────────────────────────────────────────────────

// The first worksheet as a rectangular grid of strings, with gaps filled in so
// every row has the same column indices as the header row.
export async function readXlsxRows(buf: ArrayBuffer): Promise<string[][]> {
  const view = new DataView(buf);
  const entries = readCentralDirectory(view);
  const byName = new Map(entries.map((e) => [e.name, e]));

  // Shared strings are optional — a sheet can carry inline strings only.
  let shared: string[] = [];
  const sharedEntry = byName.get("xl/sharedStrings.xml");
  if (sharedEntry) {
    const xml = await readEntry(buf, view, sharedEntry);
    // An <si> may be split across several runs (<r><t>…</t></r>); joining every
    // <t> reassembles the cell's text.
    shared = Array.from(elements(xml, "si"), (si) => textOfRuns(si.inner));
  }

  // Resolve the workbook's FIRST sheet through the relationship table; fall
  // back to the lowest-numbered sheet file when anything is unexpected.
  let sheetEntry: ZipEntry | undefined;
  try {
    const wbXml = await readEntry(buf, view, byName.get("xl/workbook.xml")!);
    const first = elements(wbXml, "sheet").next().value as XmlElement | undefined;
    const rid = first?.attrs["r:id"] ?? first?.attrs["id"];
    if (rid) {
      const relsXml = await readEntry(buf, view, byName.get("xl/_rels/workbook.xml.rels")!);
      let target: string | undefined;
      for (const rel of elements(relsXml, "Relationship")) {
        if (rel.attrs["Id"] === rid) {
          target = rel.attrs["Target"];
          break;
        }
      }
      if (target) sheetEntry = byName.get(target.replace(/^\/?(xl\/)?/, "xl/"));
    }
  } catch {
    /* fall through to the filename heuristic */
  }
  if (!sheetEntry) {
    sheetEntry = entries
      .filter((e) => /^xl\/worksheets\/sheet\d+\.xml$/.test(e.name))
      .sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }))[0];
  }
  if (!sheetEntry) throw new Error("no-worksheet");

  const sheetXml = await readEntry(buf, view, sheetEntry);
  const rows: string[][] = [];
  let width = 0;

  for (const row of elements(sheetXml, "row")) {
    const cells: string[] = [];
    for (const c of elements(row.inner, "c")) {
      const ref = c.attrs["r"] ?? "";
      const idx = ref ? columnIndex(ref) : cells.length;
      const type = c.attrs["t"];

      let value = "";
      if (type === "inlineStr") {
        value = textOfRuns(c.inner);
      } else {
        // <v> holds the stored value; for a formula cell that is the cached
        // result, which is what the spreadsheet displays.
        const v = firstValue(c.inner, "v") ?? "";
        if (type === "s") value = shared[Number(v)] ?? "";
        else if (type === "b") value = v === "1" ? "TRUE" : "FALSE";
        else value = v;
      }

      while (cells.length < idx) cells.push("");
      cells[idx] = value;
    }
    width = Math.max(width, cells.length);
    rows.push(cells);
  }

  for (const r of rows) while (r.length < width) r.push("");
  return rows;
}

export function isXlsxFilename(name: string): boolean {
  return /\.xlsx$/i.test(name);
}
